### ISSUE TITLE
Support XML/plist syntax highlighting

### ISSUE THREAD

**Issue by homebysix** [BenjaminHoegh/OneDark.novaextension#1]
When opening an XML or plist file with the One Dark theme active in Nova, syntax highlighting does not appear. Not sure whether this is a planned feature or a bug in an existing feature, but as somebody who works with a lot of plist files, adding support would be very helpful.

![](https://dev.panic.com/panic/nova-issues/uploads/3628fb8d23c449a15b5f351ea6f6a1eb/Screen_Shot_2020-08-12_at_1.36.05_PM.png)

Thank you!

**Comment by BenjaminHoegh** [comment]
the newest version should have support for this

**Comment by homebysix** [comment]
Confirmed. Thank you!

**Comment by BenjaminHoegh** [comment]
> Confirmed. Thank you!

anytime ;)
