### ISSUE TITLE
One Light

### ISSUE THREAD

**Issue by mischasigtermans** [BenjaminHoegh/OneDark.novaextension#2]
Please also make One Light.

**Comment by BenjaminHoegh** [comment]
I will do ;)

**Comment by BenjaminHoegh** [comment]
Be aware there may still be issues, but here is the first version: [Atom One Light for Nova](https://extensions.panic.com/extensions/benjaminhoegh/benjaminhoegh.OneLight/)

**Comment by mischasigtermans** [comment]
Love it! Thanks for this.
